language: node_js
node_js:
   - 12.13.0

cache:
  directories:
  - node_modules

before_install:
  - echo "Deploying"
  - npm install -g firebase-tools
  - npm install

script:
  - npm test
  

after_success:
  - travis_wait 40 npm run build
  - npm run react-scripts build
  - firebase use default --token $FIREBASE_TOKEN
  - firebase deploy -m "Travis deploy" --non-interactive --token $FIREBASE_TOKEN